name: SolUtilities
version: '${version}'
main: me.jsinco.solutilities.SolUtilities
api-version: '1.20'
author: 'Jsinco'
depend: [Vault, PlaceholderAPI]
softdepend: [PlayerPoints, SolItems, LuckPerms]
load: STARTUP
permissions:
  solutilities.prefix.staff:
    default: false
  solutilities.color.owner:
    default: false
  solutilities.color.admin:
    default: false
  solutilities.color.mod:
    default: false
  solutilities.color.builder:
    default: false
  solutilities.color.helper:
    default: false
  solutilities.color.dev:
    default: false
  solutilities.color.content:
    default: false
  solutilities.color.recruit:
    default: false
  # TODO: Add permissions
  solutilities.colorbook:
    description: Auto colors book after closing
commands:
  refer:
    description: Refer CMD
    usage: /<command> <player>
    permission: solutilities.global
  rfintl:
    description: Referrals Internal Command
    permission: solutilities.global