name: SolUtilities
version: '${version}'
main: me.jsinco.solutilities.SolUtilities
api-version: '1.20'
author: 'Jsinco'
depend: [Vault, PlaceholderAPI, OneAnnouncer]
softdepend: [PlayerPoints, SolItems, LuckPerms]
permissions:
  solutilities.prefix.staff:
    default: false
  solutilities.color.owner:
    default: false
  solutilities.color.admin:
    default: false
  solutilities.color.mod:
    default: false
  solutilities.color.builder:
    default: false
  solutilities.color.helper:
    default: false
  solutilities.color.dev:
    default: false
  solutilities.color.content:
    default: false
  solutilities.color.recruit:
    default: false
  # TODO: Add permissions
  solutilities.colorbook:
    description: Auto colors book after closing
commands:
  # Commands that are here are commands that SolUtilities needs to take priority over because another plugin is using the same command
  # Solutilities' CommandMapper cannot take priority from another plugin
  ping:
    description: Ping Command
    usage: /<command>
  refer:
    description: Refer CMD
    usage: /<command> <player>
    permission: solutilities.global
  rfintl:
    description: Referrals Internal Command
    permission: solutilities.global