name: SolUtilities
version: '${version}'
main: me.jsinco.solutilities.SolUtilities
api-version: '1.20'
author: 'Jsinco'
depend: [Vault, SolItems, PlaceholderAPI]
softdepend: [PlayerPoints]
permissions:
  solutilities.prefix.staff:
    default: false
  solutilities.color.owner:
    default: false
  solutilities.color.admin:
    default: false
  solutilities.color.mod:
    default: false
  solutilities.color.builder:
    default: false
  solutilities.color.helper:
    default: false
  solutilities.color.dev:
    default: false
  solutilities.color.content:
    default: false
  solutilities.color.recruit:
    default: false
commands:
  solace:
    description: Solace command
    permission: solutilities.global
    usage: §e/<command> <sols | sounds> <amount>
  celesteadmin:
    description: Gives a player celeste admin
    permission: solutilities.admin
    usage: /<command>
  celesteshop:
    description: Opens the celeste shop
    permission: solutilities.admin
    usage: /<command> <player>
  modelitem:
    description: Gives a player a model item
    permission: solutilities.admin
    usage: /<command> <player> <model>
  lunaadmin:
    description: Gives a player luna admin
    permission: solutilities.admin
    usage: /<command>
  lunawrapper:
    description: Gives a player a luna wrapper
    permission: solutilities.admin
    usage: /<command> <player>
  ariesmisc:
    description: Gives a player aries misc
    permission: solutilities.admin
    usage: /<command> <player>
  ranks:
    description: Ranks GUI
  welcomes:
    description: Welcomes from SolUtilities
    permission: solutilities.global
  furniture:
    description: Furniture Command
    permission: solutilities.global
    usage: /<command>
  itemprofiler:
    description: Item Profiler
    permission: solutilities.global
    usage: /<command>
    aliases: [itemprofile, profiler]
  blackmarket:
    description: The Black Market
    permission: solutilities.blackmarket
    usage: §c/<command> <add | remove | preview | market | reset | time> <dollar | solcoin | itemname | marketnumber> <player | price> <weight> <stock>
    aliases: [bm]
  refer:
    description: Refer CMD
    usage: /<command> <player>
    permission: solutilities.global
  rfintl:
    description: Referrals Internal Command
    permission: solutilities.global
  solutilities:
    description: SolUtilities Command